name: "Build and push versions"

concurrency:
  group: ci-release-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

permissions:
  contents: write
  pull-requests: write



jobs:
  bump_version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        item: ["k3s", "sbctl", "tailscale", "helm", "k9s", "nebula", "pulumi_esc", "habitat", "incus", "openbao", "alloy", "speedtest", "miniupnpc"]
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry:  ${{ secrets.OCI_REGISTRY || 'quay.io' }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - uses: actions/checkout@v4
      - name: Run updater script for ${{ matrix.item }}
        env:
          REPOSITORY: ${{ format('{0}/{1}', secrets.OCI_REGISTRY || 'quay.io', secrets.OCI_REGISTRY_NAME || 'itxaka') }}
          PUSH: true
          KEEP_FILES: false
        run: |
          ./${{ matrix.item }}.sh