name: "Build images"

concurrency:
  group: ci-build-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: PUSH=true ./build.sh